### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by miguel-guedes**

### CODE REVIEW

**Comment by BurntSushi** [comment]
@miguel-guedes Oh, I think this PR supercedes #7? I think you might have still missed `Xhr.ajax` here: https://github.com/miguel-guedes/dossier.js/blob/fix-typo/src/Dossier.js#L400 It looks like you [caught the other one](https://github.com/miguel-guedes/dossier.js/blob/fix-typo/src/Dossier.js#L67).

**Comment by miguel-guedes** [comment]
(replying here as my email reply didn't work, it seems)

I forgot to commit and push the last fix -- had it working on Sorting Desk's repo though.

Should be good to go now.

**Comment by BurntSushi** [comment]
Ah great. Looks like sauce labs is broken. :-( I'll look into it.

**Comment by BurntSushi** [comment]
Thanks!

**Pull request merged**
